fix: nbc not use correct image for downstream + cleanup downstream path
opendatahub-io/opendatahub-operator pull request #1226
Opened 2024-09-09 15:53 UTC by zdtsw

## Description

- fix wrong caller on notebookControllerPath
 this is the problem when we have reconcile twice on odh-notebook-controller see https://issues.redhat.com/browse/RHOAIENG-12732
 old: DeployManifestsFromPath on notebookControllerPath, then update params.env file. 
 new: update params.env file then do call  DeployManifestsFromPath on notebookControllerPath
- remove downstream speicific path for notebook:  `notebookImagesPathSupported` is removed (along with defaultKustomizePathSupported) , see downstream [PR](https://github.com/red-hat-data-services/rhods-operator/pull/343)
- move default workbench namespace into const
- removed duplicated comments, probably from rebase long time ago

a similar PR in downstream https://github.com/red-hat-data-services/rhods-operator/pull/343, since it also need to change the path so i cannot just have sync to it.

with these two PRs, the code in ODH and downstream should be 100% the same for workbenches.

https://issues.redhat.com/browse/RHOAIENG-12732

## How Has This Been Tested?

local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.14.910-0
- install build
- create DSC with workbench enabled
- CM notebook is created
-  CM notebooks-parameters is created
- 13 imagestreams CR created
- kf-notebook controller quay.io/opendatahub/kubeflow-notebook-controller:1.7-5d51c2b is running 
- odh-notebook controller pods quay.io/opendatahub/odh-notebook-controller:1.7-5d51c2b is running

## Screenshot or short clip

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-09-09 16:01 UTC, harshad16 requested changes
Till i understand the code-base, this is reference to old path , that was maintained in the odh-manifests.
i believe it was correct: https://github.com/red-hat-data-services/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/kustomization.yaml
there is no folder: /jupyterhub/notebooks/base

is that a correct understanding or am i missing something ?

2024-09-09 17:13 UTC, zdtsw commented
> Till i understand the code-base, this is reference to old path , that was maintained in the odh-manifests. i believe it was correct: https://github.com/red-hat-data-services/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/kustomization.yaml there is no folder: /jupyterhub/notebooks/base
> 
> is that a correct understanding or am i missing something ?

it is a little bit tricky
i think back to we just started v2, there was a difference of manifests structure in ODH and RHOAI.
so we make a different way
in ODH https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/get_all_manifests.sh#L16
in RHOAI: https://github.com/red-hat-data-services/rhods-operator/blob/main/get_all_manifests.sh#L17 

this basically leads to for the RHOAI path it is point to jupyterhub/notebooks

one thing might be easier to narrow these gaps:  is there any difference in manifests structure still between ODH and RHOAI for workbenches (both notebook and nbc)
if the answer is "no" i can do more updates on workbenches on top of this PR

2024-09-10 09:07 UTC, harshad16 commented
> it is a little bit tricky i think back to we just started v2, there was a difference of manifests structure in ODH and RHOAI. so we make a different way in ODH https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/get_all_manifests.sh#L16 in RHOAI: https://github.com/red-hat-data-services/rhods-operator/blob/main/get_all_manifests.sh#L17
> 
> this basically leads to for the RHOAI path it is point to jupyterhub/notebooks
> 
> one thing might be easier to narrow these gaps: is there any difference in manifests structure still between ODH and RHOAI for workbenches (both notebook and nbc) if the answer is "no" i can do more updates on workbenches on top of this PR


Ack, on the explanation.
However, I'm still confused about the path: `jupyterhub/notebooks`

Currently the upstream and downstream. manifests are synced for both Notebook and NBC. 
The only difference is the param file with different content in them.
example: 
Notebook:
- https://github.com/opendatahub-io/notebooks/tree/main/manifests
- https://github.com/red-hat-data-services/notebooks/tree/main/manifests

2024-09-10 09:40 UTC, zdtsw commented
> > it is a little bit tricky i think back to we just started v2, there was a difference of manifests structure in ODH and RHOAI. so we make a different way in ODH https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/get_all_manifests.sh#L16 in RHOAI: https://github.com/red-hat-data-services/rhods-operator/blob/main/get_all_manifests.sh#L17
> > this basically leads to for the RHOAI path it is point to jupyterhub/notebooks
> > one thing might be easier to narrow these gaps: is there any difference in manifests structure still between ODH and RHOAI for workbenches (both notebook and nbc) if the answer is "no" i can do more updates on workbenches on top of this PR
> 
> Ack, on the explanation. However, I'm still confused about the path: `jupyterhub/notebooks`
> 
> Currently the upstream and downstream. manifests are synced for both Notebook and NBC. The only difference is the param file with different content in them. example: Notebook:
> 
> * https://github.com/opendatahub-io/notebooks/tree/main/manifests
> * https://github.com/red-hat-data-services/notebooks/tree/main/manifests

I did some new changes this morning, 
i think this will be easier to review: in short, the "jupyter" is removed. so we only have one path for notebook image for both ODH and RHOAI

2024-09-10 12:07 UTC, jstourac commented
I can't really talk about the path changes. The code logic having the manifest deployment after it is patched makes sense though.

I also tested IIB on my cluster and tried to delete the operator pod as described in https://issues.redhat.com/browse/RHOAIENG-12409 and correct image for both notebook related deployments was used as expected, which is fine.

2024-09-10 19:47 UTC, harshad16 reviewed
lgtm
thanks for the explanation

2024-09-12 14:08 UTC, VaishnaviHire approved these changes
/lgtm

2024-09-12 14:11 UTC, merged