update: remove dsp with v1(tekton)backend related code
opendatahub-io/opendatahub-operator pull request #1281
Opened 2024-10-08 13:48 UTC by zdtsw

no need review at the moment, lets wait and see how these images will be if we can totally remove the logic

## Description

- images
- tekton rbac
- descriptions

https://issues.redhat.com/browse/RHOAIENG-14120

## How Has This Been Tested?

## Screenshot or short clip

## Merge criteria

- [ ] You have read the [contributors guide](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/CONTRIBUTING.md).
- [ ] Commit messages are meaningful - have a clear and concise summary and detailed explanation of what was changed and why.
- [ ] Pull Request contains a description of the solution, a link to the JIRA issue, and to any dependent or related Pull Request.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-10-24 15:15 UTC, HumairAK requested changes

2024-10-24 15:15 UTC, HumairAK commented on components/datasciencepipelines/datasciencepipelines.go
> +		"IMAGES_ARGOEXEC":                "RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_ARGOEXEC_IMAGE",
```suggestion
		"IMAGES_ARGO_EXEC":                "RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_ARGOEXEC_IMAGE",
```

2024-10-24 15:15 UTC, HumairAK commented on components/datasciencepipelines/datasciencepipelines.go
> +		"IMAGES_ARGOEXEC":                "RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_ARGOEXEC_IMAGE",
reference [here](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env)

2024-10-24 15:16 UTC, HumairAK commented
aside from comment above lgtm

2024-10-25 12:30 UTC, VaishnaviHire commented
Are these not built in CPaaS https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L10-#L11 ?

cc: @HumairAK

2024-10-25 13:31 UTC, zdtsw commented
> Are these not built in CPaaS https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L10-#L11 ?
> 
> cc: @HumairAK

these are borrowed from other products by pipeline

2024-10-27 08:45 UTC, merged