[WIP] Read env variables from KfDef Parameters
opendatahub-io/opendatahub-operator pull request #180
Opened 2022-10-14 12:39 UTC by VaishnaviHire

Fixes #179 

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2022-10-19 11:31 UTC, samuelvl requested changes
It works fine if I define the parameters as following:

```yaml
parameters:
  - name: minimal-image
    value: $MINIMAL_IMAGE
```

Or

```yaml
parameters:
  - name: minimal-image
    value: quay.io/modh/odh-minimal-notebook-container:v1.18.0-2
```

However when using ${VAR} it doesn't work:

```yaml
parameters:
  - name: minimal-image
    value: ${MINIMAL_IMAGE}
```

I see the following error in the operator logs:

```shell
time="2022-10-19T11:28:35Z" level=warning msg="Encountered error applying application notebook-images:  (kubeflow.error): Code 500 with message: Apply.Run : ImageStream.image.openshift.io \"s2i-minimal-notebook\" is invalid: [[]: Internal error: imagestreams \"s2i-minimal-notebook\" is invalid: spec.tags[v0.3.0-py38].from.name: Invalid value: \"\": must be of the form <tag>, <repo>:<tag>, <id>, or <repo>@<id>, spec.tags[v0.3.0-py38].from.name: Required value]"
time="2022-10-19T11:28:35Z" level=warning msg="Will retry in 4 seconds."
``` 

I'm missing some unit tests to cover the `getParameterValue` function.

2022-10-19 17:56 UTC, Jooho commented
@VaishnaviHire  keep in mind when the value is specified like the following:
~~~
parameters:
  - name: minimal-image
    value: ${MINIMAL_IMAGE}
~~~
In the pod, it will be changed like the following
~~~
parameters:
  - name: minimal-image
    value: '${MINIMAL_IMAGE}'
~~~
I am not sure your code will be impacted by this or not but I just want you to head up this kind openshift manifest behavior.

2022-10-20 10:20 UTC, VaishnaviHire commented
> @VaishnaviHire keep in mind when the value is specified like the following:
> 
> ```
> parameters:
>   - name: minimal-image
>     value: ${MINIMAL_IMAGE}
> ```
> 
> In the kfdef object, it will be changed like the following
> 
> ```
> parameters:
>   - name: minimal-image
>     value: '${MINIMAL_IMAGE}'
> ```
> 
> I am not sure your code will be impacted by this or not but I just want you to head up this kind openshift manifest behavior.

Thanks ! This should not impact the code.

2022-10-20 10:21 UTC, VaishnaviHire commented
@samuelvl Addressed the comments and updated the operator image

To run unit tests, use the following command
```
go test -run  TestGetParameterValue ./ -v
```

2022-10-20 11:25 UTC, samuelvl commented on pkg/kfapp/kustomize/kustomize.go
> +		}
It works great now! Only one question, is this `return value` really needed?

```suggestion
		}
``` 

Running the coverage of this function I found that if I remove it we can achieve 100%

```shell
# With return value
$ go test -run TestGetParameterValue -v -covermode=count -coverprofile coverage ./pkg/kfapp/kustomize/...
$ go tool cover -func=coverage
github.com/kubeflow/kfctl/v3/pkg/kfapp/kustomize/kustomize.go:1467:	getParameterValue			90.9%

# After applying the suggestion
$ go test -run TestGetParameterValue -v -covermode=count -coverprofile coverage ./pkg/kfapp/kustomize/...
$ go tool cover -func=coverage
github.com/kubeflow/kfctl/v3/pkg/kfapp/kustomize/kustomize.go:1467:	getParameterValue			100.0%
```

2022-10-20 12:16 UTC, samuelvl approved these changes
/lgtm

2022-10-20 21:31 UTC, Jooho commented
/lgtm

2022-10-21 15:56 UTC, samuelvl commented
@LaVLaS Could you approve this PR? :)

2022-11-10 18:14 UTC, VaishnaviHire commented
@LaVLaS Did you get a chance to review this ? I think this can be merged for 1.4.1

2022-11-10 21:38 UTC, LaVLaS commented
/approve

2022-11-10 22:59 UTC, merged