add manifests for odh-model-controller and model-mesh
opendatahub-io/opendatahub-operator pull request #639
Opened 2023-10-17 19:10 UTC by VedantMahabaleshwarkar

## Description

- Added model-mesh and odh-model-controller manifests to `get_all_manifests.sh` 
- added logic to allow kserve and model-mesh to share a singular odh-model-controller deployment 

## Testing 
The testing for this PR is to be done along with the testing for [this](https://github.com/opendatahub-io/odh-model-controller/pull/92) and [this](https://github.com/opendatahub-io/modelmesh-serving/pull/221) PR since they target the same set of overall changes. 
The ODH operator image has been built with the following changes : 
- odh-model-controller manifests are pre built from https://github.com/opendatahub-io/odh-model-controller/tree/remove_kserve_flag which has equivalent changes to this repo, except that it deploys the image `quay.io/vedantm/odh-model-controller:remove-kserve-flag` which contains the changes for this PR. 
- model-mesh manifests are pre built from https://github.com/opendatahub-io/modelmesh-serving/tree/manifests_transition_v2 and the manfest location is opendatahub/manifests. These manifests are now no longer bundled with odh-model-controller manifests 
- opendatahub-operator reconciliation for kserve and modelmesh allow a common deployment of odh-model-controller

## How Has This Been Tested?

#### ModelMesh testing
- cluster login
- `git clone git@github.com:VedantMahabaleshwarkar/opendatahub-operator.git`
- `cd opendatahub-operator` 
- switch to branch `transition`
- `make deploy -e IMG=quay.io/vedantm/opendatahub-operator:version_builtin` 
- This will install the ODH operator in NS `opendatahub-operator-system` with the image `quay.io/vedantm/opendatahub-operator:version_builtin`
- create the following DSC in NS `opendatahub` 
```
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: example
spec:
  components:
    modelmeshserving:
      managementState: Managed
```
- deploy and test a model with modelmesh 

#### Kserve testing
```
Note: Cleanup kserve CRDs before testing modelmesh
```
- cluster login
- install ODH Kserve + dependencies stack by following [instructions](https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/install-manual.md)
```
Note: Only install the dependencies, the ODH operator will be a custom install according to next steps
```
- `git clone git@github.com:VedantMahabaleshwarkar/opendatahub-operator.git`
- `cd opendatahub-operator` 
- switch to branch `transition`
- `make deploy -e IMG=quay.io/vedantm/opendatahub-operator:version_builtin` 
- This will install the ODH operator in NS `opendatahub-operator-system` with the image `quay.io/vedantm/opendatahub-operator:version_builtin`
- create the following DSC in NS `opendatahub` 
```
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
    kserve:
      managementState: Managed
```
- deploy and test a kserve model using [instructions](https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/deploy-remove-scripts.md)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-10-17 19:14 UTC, VedantMahabaleshwarkar commented
Custom ODH operator image was built with the following settings in `get_all_manifests.sh` for the operator : 
```
["odh-model-controller"]="VedantMahabaleshwarkar:odh-model-controller:manifests_transition_test:config:odh-model-controller"
["model-mesh"]="VedantMahabaleshwarkar:modelmesh-serving:manifests_overlay:config:model-mesh"
```

2023-10-20 16:03 UTC, VaishnaviHire requested changes

2023-10-20 16:03 UTC, VaishnaviHire commented on components/kserve/kserve.go
> +		if err := deploy.DeployManifestsFromPath(cli, owner, DependentPath, dscispec.ApplicationsNamespace, k.GetComponentName(), enabled); err != nil {
This should be outside `if enabled` condition. Reason being DeployManifestsFromPath function takes the enable value to either `deploy` or `delete` component manifests

2023-10-20 16:03 UTC, VaishnaviHire commented on components/modelmeshserving/modelmeshserving.go
> +	}
This should be also outside `if enabled` condition

2023-10-20 16:08 UTC, VaishnaviHire commented
@VedantMahabaleshwarkar Can you also fix the linter issues?

2023-10-20 16:56 UTC, VaishnaviHire approved these changes

2023-10-20 17:51 UTC, VaishnaviHire reviewed
/lgtm

2023-10-20 18:51 UTC, VaishnaviHire commented
/test opendatahub-operator-e2e

2023-10-20 18:53 UTC, VaishnaviHire commented
Tests successful locally

/lgtm

2023-10-20 18:54 UTC, merged