WIP:ODH release 1.0 manifest
opendatahub-io/opendatahub-operator pull request #84
Opened 2021-01-27 05:03 UTC by LaVLaS

Adds the v1.0 release OLM manifest that will be submitted to OperatorHub for community operators

2021-01-27 23:17 UTC, nakfour commented on deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml
> +
Typo "is released"

2021-01-28 15:02 UTC, anishasthana requested changes

2021-01-28 15:02 UTC, anishasthana commented on deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml
> +    The Open Data Hub is a machine-learning-as-a-service platform built on Red Hat's Kubernetes-based OpenShift® Container Platform. Open Data Hub integrates multiple AI/ML open source components int
NIT: Openshift -> OpenShift

2021-01-29 14:46 UTC, nakfour commented on deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml
> +
@LaVLaS one more fix, please use the raw url for kfdef "https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_openshift.v1.2.0.yaml"

2021-01-29 16:40 UTC, nakfour approved these changes

2021-01-29 16:51 UTC, LaVLaS commented on deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml
> +    The Open Data Hub is a machine-learning-as-a-service platform built on Red Hat's Kubernetes-based OpenShift® Container Platform. Open Data Hub integrates multiple AI/ML open source components int
Good catch

2021-01-29 17:04 UTC, nakfour approved these changes

2021-01-29 18:38 UTC, anishasthana approved these changes
/lgtm

2021-02-01 16:24 UTC, nakfour approved these changes

2021-02-03 14:36 UTC, LaVLaS commented
/retest

2021-02-03 16:20 UTC, merged